
meta_product_name: "Mita Group"
meta_title: "MITA Group - Full Service eCommerce Agency"
meta_description: "MITA Group develops fast and responsive online stores. Our video ads, photo content and PPC advertising strategies will boost your sales instantly."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@MITAGroup"   # required for Twitter Cards
